"""SQLite engine, session, ORM models, and lightweight column migrations.

Split into base/models/engine/migrations submodules; everything stays
importable from `app.core.db` itself, which is how the rest of the app
(api, ingest, profile, retrieval, evals) refers to all of it.
"""

from __future__ import annotations

from app.core.db.base import Base
from app.core.db.engine import (
    _backup_sqlite_file,
    _configure_sqlite,
    get_db,
    get_engine,
    logger,
    reset_engine,
)
from app.core.db.migrations import (
    _migrate_accounts_contact_columns,
    _migrate_contact_items,
    _migrate_job_postings_account_id,
    _migrate_job_postings_extraction_columns,
    _migrate_job_postings_tracking_columns,
    _migrate_llm_calls_attribution_columns,
    _migrate_rate_limit_events_account_column,
    _migrate_repositories_curation_columns,
    _migrate_resumes_build_columns,
    _migrate_resumes_name_column,
    init_db,
)
from app.core.db.models import (
    Account,
    ApiKey,
    AppSetting,
    AuthSource,
    ContactEmail,
    ContactPhone,
    Detection,
    Education,
    EmbeddingCache,
    Experience,
    ExperiencePoint,
    ExperienceSkillEvidence,
    JobPosting,
    LLMCall,
    MatchResult,
    Profile,
    ProjectLink,
    RateLimitEvent,
    Repository,
    Resume,
    RoleFamily,
    Skill,
    SkillEvidence,
    SkillMapCache,
    SkillStar,
    SkillVerdict,
    SocialLink,
    SyncSource,
)

__all__ = [
    "Account",
    "ApiKey",
    "AppSetting",
    "AuthSource",
    "Base",
    "ContactEmail",
    "ContactPhone",
    "Detection",
    "Education",
    "EmbeddingCache",
    "Experience",
    "ExperiencePoint",
    "ExperienceSkillEvidence",
    "JobPosting",
    "LLMCall",
    "MatchResult",
    "Profile",
    "ProjectLink",
    "RateLimitEvent",
    "Repository",
    "Resume",
    "RoleFamily",
    "Skill",
    "SkillEvidence",
    "SkillMapCache",
    "SkillStar",
    "SkillVerdict",
    "SocialLink",
    "SyncSource",
    "_backup_sqlite_file",
    "_configure_sqlite",
    "_migrate_accounts_contact_columns",
    "_migrate_contact_items",
    "_migrate_job_postings_account_id",
    "_migrate_job_postings_extraction_columns",
    "_migrate_job_postings_tracking_columns",
    "_migrate_llm_calls_attribution_columns",
    "_migrate_rate_limit_events_account_column",
    "_migrate_repositories_curation_columns",
    "_migrate_resumes_build_columns",
    "_migrate_resumes_name_column",
    "get_db",
    "get_engine",
    "reset_engine",
    "init_db",
    "logger",
]
